# Preprocesses the dataset to separate the metrics for the different edge devices

In [25]:
import pandas as pd
import numpy as np

In [26]:
search_space = 'nasbench201'

In [27]:
df = pd.read_csv(f'../{search_space}_cifar10.csv')
df.head()

,Architectures,Accuracy,EdgeGPU_Lat,EdgeTPU_Lat,Raspi4_Lat,Eyeriss_Lat,Pixel3_Lat,FPGA_Lat
0,"|1_Convolution:(num_filters=16, kernel_size=3)...",69.55,5.807419,0.957181,10.481977,3.64562,3.60585,2.57296
1,"|1_Convolution:(num_filters=16, kernel_size=3)...",88.22,6.547689,1.438988,54.777398,7.57778,17.23810,5.31536
2,"|1_Convolution:(num_filters=16, kernel_size=3)...",69.95,6.509256,2.030067,50.409404,10.52690,15.72300,5.28656
3,"|1_Convolution:(num_filters=16, kernel_size=3)...",78.51,2.412014,0.389997,2.923992,3.15410,1.06264,1.54256
4,"|1_Convolution:(num_filters=16, kernel_size=3)...",71.71,4.385161,0.698665,7.582405,2.17106,2.35423,2.16336

In [28]:
# edge_gpu_df = df[['Architectures', 'Accuracy', 'Memory', 'EdgeGPU_Lat']].copy() # NAS-Bench201
edge_gpu_df = df[['Architectures', 'EdgeGPU_Lat']].copy()  # FBNet
edge_gpu_df.rename(columns={'EdgeGPU_Lat': 'Latency'}, inplace=True)
edge_gpu_df.to_csv(f'profiled_nets/{search_space}_edgegpu.csv', index=False)
edge_gpu_df

                                           Architectures   Latency
0      |1_Convolution:(num_filters=16, kernel_size=3)...  5.807419
1      |1_Convolution:(num_filters=16, kernel_size=3)...  6.547689
2      |1_Convolution:(num_filters=16, kernel_size=3)...  6.509256
3      |1_Convolution:(num_filters=16, kernel_size=3)...  2.412014
4      |1_Convolution:(num_filters=16, kernel_size=3)...  4.385161
...                                                  ...       ...
15620  |1_Convolution:(num_filters=16, kernel_size=3)...  2.443252
15621  |1_Convolution:(num_filters=16, kernel_size=3)...  2.823582
15622  |1_Convolution:(num_filters=16, kernel_size=3)...  5.351725
15623  |1_Convolution:(num_filters=16, kernel_size=3)...  4.870882
15624  |1_Convolution:(num_filters=16, kernel_size=3)...  5.891724

[15625 rows x 2 columns]

In [29]:
# FBNet does not have Edge TPU
edge_tpu_df = df[['Architectures', 'Accuracy', 'EdgeTPU_Lat']].copy()
edge_tpu_df.rename(columns={'EdgeTPU_Lat': 'Latency'}, inplace=True)
edge_tpu_df.to_csv(f'profiled_nets/{search_space}_edgetpu.csv', index=False)
edge_tpu_df.head()

                                       Architectures  Accuracy   Latency
0  |1_Convolution:(num_filters=16, kernel_size=3)...     69.55  0.957181
1  |1_Convolution:(num_filters=16, kernel_size=3)...     88.22  1.438988
2  |1_Convolution:(num_filters=16, kernel_size=3)...     69.95  2.030067
3  |1_Convolution:(num_filters=16, kernel_size=3)...     78.51  0.389997
4  |1_Convolution:(num_filters=16, kernel_size=3)...     71.71  0.698665

In [30]:
# raspi4_df = df[['Architectures', 'Accuracy','Memory', 'Raspi4_Lat']].copy()
raspi4_df = df[['Architectures', 'Raspi4_Lat']].copy()
raspi4_df.rename(columns={'Raspi4_Lat': 'Latency'}, inplace=True)
raspi4_df.to_csv(f'profiled_nets/{search_space}_raspi4.csv', index=False)
raspi4_df.head()

                                       Architectures    Latency
0  |1_Convolution:(num_filters=16, kernel_size=3)...  10.481977
1  |1_Convolution:(num_filters=16, kernel_size=3)...  54.777398
2  |1_Convolution:(num_filters=16, kernel_size=3)...  50.409404
3  |1_Convolution:(num_filters=16, kernel_size=3)...   2.923992
4  |1_Convolution:(num_filters=16, kernel_size=3)...   7.582405

In [31]:
# eyeriss_df = df[['Architectures', 'Accuracy', 'Memory', 'Eyeriss_Lat']].copy()
eyeriss_df = df[['Architectures', 'Eyeriss_Lat']].copy()
eyeriss_df.rename(columns={'Eyeriss_Lat': 'Latency'}, inplace=True)
eyeriss_df.to_csv(f'profiled_nets/{search_space}_eyeriss.csv', index=False)
eyeriss_df.head()

                                       Architectures   Latency
0  |1_Convolution:(num_filters=16, kernel_size=3)...   3.64562
1  |1_Convolution:(num_filters=16, kernel_size=3)...   7.57778
2  |1_Convolution:(num_filters=16, kernel_size=3)...  10.52690
3  |1_Convolution:(num_filters=16, kernel_size=3)...   3.15410
4  |1_Convolution:(num_filters=16, kernel_size=3)...   2.17106

In [32]:
# pixel3_df = df[['Architectures', 'Accuracy', 'Memory', 'Pixel3_Lat']].copy()
pixel3_df = df[['Architectures', 'Pixel3_Lat']].copy()
pixel3_df.rename(columns={'Pixel3_Lat': 'Latency'}, inplace=True)
pixel3_df.to_csv(f'profiled_nets/{search_space}_pixel3.csv', index=False)
pixel3_df.head()

                                       Architectures   Latency
0  |1_Convolution:(num_filters=16, kernel_size=3)...   3.60585
1  |1_Convolution:(num_filters=16, kernel_size=3)...  17.23810
2  |1_Convolution:(num_filters=16, kernel_size=3)...  15.72300
3  |1_Convolution:(num_filters=16, kernel_size=3)...   1.06264
4  |1_Convolution:(num_filters=16, kernel_size=3)...   2.35423

In [33]:
# fpga_df = df[['Architectures', 'Accuracy', 'Memory', 'FPGA_Lat']].copy()
fpga_df = df[['Architectures', 'FPGA_Lat']].copy()
fpga_df.rename(columns={'FPGA_Lat': 'Latency'}, inplace=True)
fpga_df.to_csv(f'profiled_nets/{search_space}_fpga.csv', index=False)
fpga_df.head()

                                       Architectures  Latency
0  |1_Convolution:(num_filters=16, kernel_size=3)...  2.57296
1  |1_Convolution:(num_filters=16, kernel_size=3)...  5.31536
2  |1_Convolution:(num_filters=16, kernel_size=3)...  5.28656
3  |1_Convolution:(num_filters=16, kernel_size=3)...  1.54256
4  |1_Convolution:(num_filters=16, kernel_size=3)...  2.16336